package com.locus.dao;

import com.locus.model.ValuationReport;

import java.util.List;
import java.util.Optional;

/**
 * DAO for persisting and retrieving valuation report metadata.
 *
 * <p>The actual PDF bytes are stored on disk; only the report metadata
 * (sections, analyst notes, file path) is persisted here.</p>
 */
public interface ValuationReportDAO {

    /**
     * Inserts a new report record.
     *
     * @param report the report to persist
     * @return true if the row was inserted
     */
    boolean insert(ValuationReport report);

    /**
     * Finds a report by its unique ID.
     *
     * @param reportId the report ID
     * @return the report, or empty if not found
     */
    Optional<ValuationReport> findById(String reportId);

    /**
     * Returns all reports generated for a specific property.
     *
     * @param propertyId the property ID
     * @return list of reports, newest first
     */
    List<ValuationReport> findByProperty(String propertyId);

    /**
     * Returns all reports generated by a specific analyst.
     *
     * @param analystId the analyst's user ID
     * @return list of reports, newest first
     */
    List<ValuationReport> findByAnalyst(String analystId);

    /**
     * Updates the pdf_file_path after a PDF is saved to disk.
     *
     * @param reportId the report ID
     * @param filePath absolute path to the saved PDF
     * @return true if the row was updated
     */
    boolean updateFilePath(String reportId, String filePath);
}
