db.url=jdbc:postgresql://localhost:5432/locus_analytics
db.username=postgres
db.password=password

# GOOGLE MAPS (Phase 2 - Ayaan will use this)
google.maps.api.key=REPLACE_WITH_API_KEY

# ML MODEL (Phase 2 - Arham will generate this)
model.file.path=REPLACE_WITH_MODEL_PATH